.deploy_webserver_on_linux_template: &deploy_webserver_on_linux
    script:
        - echo "deploying on $HOST"
        - cd $PROJECT_FOLDER
        - dotnet restore
        - dotnet build --configuration $CONFIGURATION
        - dotnet publish --configuration $CONFIGURATION --framework $FRAMEWORK --self-contained true --runtime linux-x64
        - cd bin/$CONFIGURATION/$FRAMEWORK/linux-x64
        - apt-get update -qy
        - apt-get install -y lftp
        - echo "push .net core to $HOST"
        - lftp -e "mirror -R publish/ /var/www/$PUBLISH_FOLDER ; exit" -u $SSH_USERNAME,$SSH_PASSWORD sftp://$HOST
        - echo "done!"

stages:
    - build
    - deploy

variables:
    FRAMEWORK: "netcoreapp3.1"
    HOST: "80.211.230.253"

before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_api_service:
    stage: build
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "production"'
    script:
        - cd VVVVID-Downloader/VVVVID-Downloader.WebApi
        - dotnet restore
        - dotnet build -- configuration Debug

deploy_api_service:
    stage: deploy
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    rules:
        - if: '$CI_COMMIT_REF_NAME == "production"'
    variables:
        CONFIGURATION: "Release"
        SSH_USERNAME: "$USERHOST"
        SSH_PASSWORD: "$PASSWORDHOST"
        PROJECT_FOLDER: "VVVVID-Downloader/VVVVID-Downloader.WebApi"
        PUBLISH_FOLDER: "VVVVID-Downloader.WebApi"
    <<: *deploy_webserver_on_linux
    after_script:
        # riavvio servizio
        - apt-get install -y sshpass
        - sshpass -p $SSH_PASSWORD ssh $SSH_USERNAME@$HOST systemctl restart kestrel-VVVVID-Downloader.WebApi.service

build_ui:
    stage: build
    rules:
        - if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "production"'
    image: registry.gitlab.com/projects-experimenta/cre-tv:angular-cli-9.1.6
    script:
        - cd angular-client
        - npm i
        - ng build

deploy_ui:
    stage: deploy
    rules:
        - if: '$CI_COMMIT_REF_NAME == "production"'
    image: registry.gitlab.com/projects-experimenta/cre-tv:angular-cli-9.1.6
    script: 
        - cd angular-client
        - npm i
        - ng build --prod
        - echo "push angular-client to $HOST"
        - chmod 644 ~/.ssh/known_hosts
        - lftp -e "mirror -R dist/angular-client/ /var/www/angular-client ; exit" -u $USERHOST,$PASSWORDHOST sftp://$HOST
        - echo "done!"
